import ProductShell from "@/components/ProductShell";
import { trpc } from "@/lib/trpc";
import { Bar, BarChart, CartesianGrid, Legend, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { GitCompareArrows, ShieldAlert, Target } from "lucide-react";
import { useMemo, useState } from "react";

const NONE = "__none__";
const colors = ["#19c39a", "#d99a5f", "#a894ff", "#e7bd64"];
const labels: Record<string,string> = { weekly:"1W", "4weeks":"4W", ytd:"YTD", last12m:"12M", "1y":"1Y", "2y":"2Y", "3y":"3Y", "4y":"4Y", "5y":"5Y", "6y":"6Y", P:"Performance", R:"Risk", B:"Benchmark", C:"Consistency", I:"Real Return" };
const fmt = (value:number | null | undefined) => value === null || value === undefined ? "—" : new Intl.NumberFormat("en-US", { maximumFractionDigits:1, minimumFractionDigits:1, useGrouping:false }).format(value);
const median = (values:number[]) => { const sorted = [...values].sort((a,b) => a-b); return sorted.length ? (sorted[Math.floor((sorted.length-1)/2)] + sorted[Math.ceil((sorted.length-1)/2)]) / 2 : null; };
type Fund = { fundId:string; canonicalName:string; category:string|null; smartScore:number|null; evidenceScore:number|null; naturalBenchmark:string|null; components:Record<"P"|"R"|"B"|"C"|"I",number|null>; returns:Record<string,number|null> };

function Unavailable({ text }: { text:string }) { return <div className="compare-unavailable"><ShieldAlert size={20}/><p>{text}</p></div>; }

function FundVisualComparison({ funds, componentRows, commonHorizons }: { funds:Fund[]; componentRows:Array<Record<string,string | number>>; commonHorizons:string[] }) {
  const horizonRows = useMemo(() => commonHorizons.map(horizon => Object.fromEntries([["period", labels[horizon]], ...funds.map(fund => [fund.canonicalName, fund.returns[horizon]!])])), [funds, commonHorizons]);
  const scatter = useMemo(() => funds.filter(fund => fund.components.P !== null && fund.components.R !== null).map(fund => ({ x:fund.components.P!, y:fund.components.R!, z:Math.max(fund.evidenceScore ?? 0, 1), name:fund.canonicalName })), [funds]);
  return <section className="compare-visuals">
    <div className="compare-visual-heading"><div><p className="eyebrow">VISUAL COMPARISON / ALIGNED INPUTS</p><h2>طبقات المقارنة المرئية</h2></div><p>كل رسم مبني فقط على المحاور والفترات المشتركة بين الأطراف المحددة.</p></div>
    <div className="compare-visual-grid">
      <article className="compare-visual-card"><header><div><Target size={17}/><p className="eyebrow">DNA OVERLAY</p><h3>تراكب بصمة SmartScore</h3></div><span>{componentRows.length} محاور مشتركة</span></header>{componentRows.length >= 3 ? <ResponsiveContainer width="100%" height={290}><RadarChart data={componentRows}><PolarGrid stroke="#315b63"/><PolarAngleAxis dataKey="metric" stroke="#afc8c2" fontSize={10}/>{funds.map((fund,index) => <Radar key={fund.fundId} dataKey={fund.canonicalName} name={fund.canonicalName} stroke={colors[index]} fill={colors[index]} fillOpacity={.1}/>) }<Legend wrapperStyle={{fontSize:9}}/><Tooltip contentStyle={{background:"#071e23",border:"1px solid #35606a",fontSize:10}}/></RadarChart></ResponsiveContainer> : <Unavailable text="لا تتوفر ثلاثة محاور SmartScore مشتركة على الأقل لبناء البصمة."/>}</article>
      <article className="compare-visual-card"><header><div><Target size={17}/><p className="eyebrow">QUALITY POSITIONING</p><h3>الأداء × جودة المخاطر</h3></div><span>{scatter.length} نقاط</span></header>{scatter.length >= 2 ? <ResponsiveContainer width="100%" height={290}><ScatterChart margin={{top:10,right:10,bottom:10,left:0}}><CartesianGrid stroke="#1b454d"/><XAxis type="number" dataKey="x" name="الأداء P" domain={[0,100]} stroke="#648f89" fontSize={9}/><YAxis type="number" dataKey="y" name="المخاطر R" domain={[0,100]} stroke="#648f89" fontSize={9}/><ZAxis type="number" dataKey="z" range={[55,210]} name="قوة الأدلة"/><Tooltip cursor={{strokeDasharray:"3 3"}} contentStyle={{background:"#071e23",border:"1px solid #35606a",fontSize:10}}/><Scatter name="الصناديق" data={scatter} fill="#19c39a" fillOpacity={.8}/></ScatterChart></ResponsiveContainer> : <Unavailable text="لا تتوافر درجتا الأداء والمخاطر لكل صندوق مختار."/>}<footer>حجم النقطة يمثل قوة الأدلة، وليس حجم الصندوق.</footer></article>
      <article className="compare-visual-card compare-visual-wide"><header><div><GitCompareArrows size={17}/><p className="eyebrow">HORIZON MATRIX</p><h3>فروق آفاق الأداء المشتركة</h3></div><span>{commonHorizons.length} فترات</span></header>{commonHorizons.length ? <ResponsiveContainer width="100%" height={290}><BarChart data={horizonRows}><CartesianGrid stroke="#1b454d" vertical={false}/><XAxis dataKey="period" stroke="#648f89" fontSize={10}/><YAxis stroke="#648f89" fontSize={9}/><Tooltip contentStyle={{background:"#071e23",border:"1px solid #35606a",fontSize:10}}/><Legend wrapperStyle={{fontSize:9}}/>{funds.map((fund,index) => <Bar key={fund.fundId} dataKey={fund.canonicalName} fill={colors[index]} radius={[2,2,0,0]}/>)}</BarChart></ResponsiveContainer> : <Unavailable text="لا توجد فترة أداء مكتملة مشتركة بين جميع الصناديق المحددة."/>}</article>
    </div>
  </section>;
}

function PerformanceTable({ funds, horizons }: { funds:Fund[]; horizons:string[] }) { return horizons.length ? <section className="compare-table-wrap"><table><thead><tr><th>الفترة المشتركة</th>{funds.map(fund => <th key={fund.fundId}>{fund.canonicalName}</th>)}</tr></thead><tbody>{horizons.map(horizon => <tr key={horizon}><td>{labels[horizon]}</td>{funds.map(fund => <td className="mono" key={fund.fundId}>{fmt(fund.returns[horizon])}%</td>)}</tr>)}</tbody></table></section> : <Unavailable text="لا توجد فترة أداء مشتركة مكتملة بين الصناديق المختارة."/>; }
function CategoryComparison({ funds, universe }: { funds:Fund[]; universe:Fund[] }) { const horizons = ["weekly","4weeks","ytd","last12m","2y","3y","4y","5y","6y"]; return <section className="category-compare-list">{funds.map(fund => <article key={fund.fundId}><h3>{fund.canonicalName}</h3><p>{fund.category ?? "غير مصنف"}</p><div>{horizons.filter(horizon => fund.returns[horizon] !== null).slice(0,6).map(horizon => { const values = universe.filter(item => item.category === fund.category && item.returns[horizon] !== null).map(item => item.returns[horizon]!); const peerMedian = median(values); return <span key={horizon}><small>{labels[horizon]}</small><b className="mono">{fmt(fund.returns[horizon])}%</b><em>وسيط الفئة {peerMedian === null ? "—" : `${fmt(peerMedian)}%`}</em></span>; })}</div></article>)}</section>; }

export default function Compare() {
  const { data, isLoading, error } = trpc.platform.universe.useQuery(undefined, { retry:false, refetchOnWindowFocus:false });
  const [selected, setSelected] = useState<string[]>([]);
  const [mode, setMode] = useState<"fund"|"category"|"benchmark"|"market">("fund");
  const funds = useMemo(() => selected.reduce<Fund[]>((current, id) => {
    const fund = data?.items.find(item => item.fundId === id);
    if (fund) current.push(fund);
    return current;
  }, []), [selected, data]);
  const componentRows = useMemo(() => (["P","R","B","C","I"] as const).filter(key => funds.length >= 2 && funds.every(fund => fund.components[key] !== null)).map(key => Object.fromEntries([["metric", labels[key]], ...funds.map(fund => [fund.canonicalName, fund.components[key]!])])), [funds]);
  const commonHorizons = useMemo(() => Object.keys(labels).filter(key => !["P","R","B","C","I"].includes(key) && funds.length >= 2 && funds.every(fund => fund.returns[key] !== null)), [funds]);
  const toggle = (id:string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 4 ? [...current,id] : current);
  return <ProductShell title="مقارنة الصناديق" eyebrow="COMPARE · SIDE BY SIDE / PERIOD-ALIGNED ANALYSIS" description="قارن حتى أربعة صناديق. لا يظهر أي محور أو فترة إلا إذا كانت متاحة لكل الأطراف على أساس متوافق.">
    <section className="compare-picker"><div><GitCompareArrows size={18}/><b>اختر من 2 إلى 4 صناديق</b><small>{selected.length} / 4 محدد</small></div><div className="compare-selector-grid">{[0,1,2,3].map(slot => <select key={slot} value={selected[slot] ?? NONE} onChange={event => { const value = event.target.value; const prior = selected[slot]; if (prior) toggle(prior); if (value !== NONE && !selected.includes(value)) toggle(value); }}><option value={NONE}>اختر صندوقًا</option>{data?.items.filter(item => !selected.includes(item.fundId) || selected[slot] === item.fundId).map(item => <option key={item.fundId} value={item.fundId}>{item.canonicalName}</option>)}</select>)}</div></section>
    <div className="compare-modes">{[{id:"fund",label:"Fund vs Fund"},{id:"category",label:"Fund vs Category"},{id:"benchmark",label:"Fund vs Benchmark"},{id:"market",label:"Fund vs Market"}].map(item => <button key={item.id} className={mode === item.id ? "active" : ""} onClick={() => setMode(item.id as typeof mode)}>{item.label}</button>)}</div>
    {error ? <div className="platform-empty">تعذر تحميل بيانات المقارنة.</div> : funds.length < 2 ? <div className="platform-empty">اختر صندوقين على الأقل لبدء مقارنة متوافقة.</div> : mode === "fund" ? <><section className="compare-summary-grid">{funds.map((fund,index) => <article key={fund.fundId} style={{borderTopColor:colors[index]}}><small>{fund.category ?? "غير مصنف"}</small><h3>{fund.canonicalName}</h3><strong className="mono">{fmt(fund.smartScore)}</strong><p>SmartScore · Evidence {fmt(fund.evidenceScore)}</p></article>)}</section><FundVisualComparison funds={funds} componentRows={componentRows} commonHorizons={commonHorizons}/><PerformanceTable funds={funds} horizons={commonHorizons}/></> : mode === "category" ? <CategoryComparison funds={funds} universe={(data?.items ?? []) as Fund[]}/> : mode === "benchmark" ? <section className="benchmark-compare-grid">{funds.map(fund => <article key={fund.fundId}><small>Natural Benchmark</small><h3>{fund.canonicalName}</h3><strong>{fund.naturalBenchmark ?? "غير متاح"}</strong><p>Benchmark Score <b className="mono">{fmt(fund.components.B)}</b></p><span>{fund.components.B === null ? "لا توجد مقارنة مواءمة قابلة للحساب" : "محسوب من فترات مرجعية مشتركة"}</span></article>)}</section> : <Unavailable text="لا تُعرض مقارنة Fund vs Market حاليًا لأن سلسلة NAV التاريخية اليومية والسلاسل السوقية لا تشترك في أساس زمني كامل. لن نستخدم ETF أو CFD أو proxy بدلًا منها."/>}
    {isLoading && <div className="platform-empty">يجري تحميل عالم الصناديق…</div>}<p className="public-disclosure">المقارنة بحثية فقط. الفترات ذات البيانات الناقصة مستبعدة تلقائيًا، ولا تعني النتيجة توصية استثمارية.</p>
  </ProductShell>;
}
