import ProductShell from "@/components/ProductShell";
import { trpc } from "@/lib/trpc";
import { ArrowUpLeft, BarChart3, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const metrics = [{ id: "smart", label: "SmartScore", key: "smartScore" }, { id: "performance", label: "الأداء P", key: "P" }, { id: "risk", label: "المخاطر R", key: "R" }, { id: "benchmark", label: "المراجع B", key: "B" }, { id: "consistency", label: "الاتساق C", key: "C" }, { id: "real", label: "العائد الحقيقي I", key: "I" }, { id: "confidence", label: "قوة الأدلة", key: "evidenceScore" }] as const;
const fmt = (value: number | null | undefined, digits = 1) => value === null || value === undefined ? "—" : new Intl.NumberFormat("en-US", { maximumFractionDigits: digits, minimumFractionDigits: digits, useGrouping: false }).format(value);

export default function Rankings() {
  const [, setLocation] = useLocation(); const { data, isLoading, error } = trpc.platform.universe.useQuery(undefined, { retry: false, refetchOnWindowFocus: false });
  const [metric, setMetric] = useState<(typeof metrics)[number]["id"]>("smart"); const [category, setCategory] = useState("__all__"); const [search, setSearch] = useState("");
  const definition = metrics.find(item => item.id === metric)!;
  const rows = useMemo(() => (data?.items ?? []).filter(item => (category === "__all__" || item.category === category) && item.canonicalName.toLowerCase().includes(search.toLowerCase())).map(item => ({ item, value: definition.key in item.components ? item.components[definition.key as "P" | "R" | "B" | "C" | "I"] : definition.key === "smartScore" ? item.smartScore : item.evidenceScore })).filter(row => row.value !== null).sort((a, b) => b.value! - a.value!), [data, category, search, definition]);
  return <ProductShell title="تصنيفات الصناديق" eyebrow="RANK / SEPARATED ANALYTICAL LENSES" description="سبعة تصنيفات مستقلة؛ الأداء والمخاطر والمراجع والاتساق والعائد الحقيقي وقوة الأدلة لا تُدمج في ترتيب واحد غير قابل للتفسير."><div className="rank-tabs">{metrics.map(item => <button key={item.id} onClick={() => setMetric(item.id)} className={metric === item.id ? "active" : ""}>{item.label}</button>)}</div><section className="rank-controls"><label><Search size={14} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث باسم الصندوق" /></label><select value={category} onChange={event => setCategory(event.target.value)}><option value="__all__">كل الفئات</option>{data?.facets.categories.map(item => <option key={item} value={item}>{item}</option>)}</select><span>{fmt(rows.length, 0)} نتيجة قابلة للترتيب</span></section>{error ? <div className="platform-empty">تعذر تحميل التصنيفات. لا تُعرض نتائج بديلة.</div> : <section className="rank-board"><header><span>#</span><span>الصندوق</span><span>{definition.label}</span><span>Evidence</span><span>الأهلية</span><span /></header>{rows.slice(0, 100).map((row, index) => <article key={row.item.fundId} onClick={() => setLocation(`/funds/${encodeURIComponent(row.item.fundId)}`)}><strong className="mono rank-index">{String(index + 1).padStart(2, "0")}</strong><div><b>{row.item.canonicalName}</b><small>{row.item.category ?? "غير مصنف"}</small></div><strong className="mono rank-value">{fmt(row.value)}</strong><span className={`score-chip confidence-${(row.item.dataConfidence ?? "insufficient").toLowerCase()}`}>{fmt(row.item.evidenceScore, 0)} · {row.item.dataConfidence ?? "—"}</span><span>{row.item.qualificationStatus === "qualified" ? <span className="status-chip verified"><ShieldCheck size={12} />مؤهل</span> : <span className="status-chip pending">Raw Rank</span>}</span><ArrowUpLeft size={15} /></article>)}</section>}{isLoading && <div className="platform-empty"><BarChart3 size={20} />يجري بناء التصنيف من أحدث تقرير…</div>}{!isLoading && !rows.length && !error && <div className="platform-empty">لا تتوفر قيم قابلة للترتيب لهذا المحور والفئة حاليًا؛ لا يُستخدم الصفر بدل البيانات المفقودة.</div>}<p className="public-disclosure">كل ترتيب يعرض فقط الصناديق التي يتوفر لها المحور المحدد. Qualified Rank منفصل عن Raw Rank ولا يُمنح دون شروط الأدلة.</p></ProductShell>;
}
